### ISSUE TITLE
Create a Context Script [$21 awarded]

### ISSUE THREAD

**Issue by nathanathan** [contextscript/contextscript#1]
I am posting [a bounty](https://www.bountysource.com/issues/8198615-create-a-context-script) for publishing a Context Script and reporting any issues encountered during the process. The script will need to be added to [this directory](https://github.com/contextscript/contextscript/tree/master/contextScripts) via pull request and it should follow the format of the other scripts in there. You can test it out using an account at contextscript.com. What the script does is completely open-ended. I've listed some ideas below, but you can bring your own idea if you run it by me first and I approve. (As long as it isn't something trivial like "hello world" I will probably approve).

Here are my suggested ideas for Context Scripts:
1. query: has this been posted on reddit/hacker news?
   
   > response: Search for the current webpage on a link aggregator and optionally provide a way to post it.
2. query: Find text like "space ship"
   
   > response: Highlight words similar to the given phrase (e.g. "space shuttle", "rocket") using NLP techniques.
3. query: regex search {{regex}}
   
   > response: Find and highlight text on the webpage that matches the regular expression.
4. query: List the people mentioned on this page
   
   > response: Use Dbpedia spotlight or another entity recognition system to list all the people mentioned on a page. Could use other types of entities as well.
5. query: screenshot this page
   
   > response: Screenshot the page with http://html2canvas.hertzen.com/ and display the result.
6. query: How has this page changed recently?
   
   > response: Use the wayback machine to report things like when the page last changed, and if possible, what changed about it.
7. query: make this script into a bookmarklet
   
   > response: create a dedicated bookmarklet that invokes the previous script
8. query: word frequency histogram
   
   > Plot a word frequency histogram using the page's textual content.
9. query on evernote or google keep: find related notes
   
   > Show the top N most similar notes. One approach would be to look for correlations in their bag-of-words tf-idf vectors.
10. query on cloud9 ide: filter nulls out of the list
    
    > Inject code at the location of the cursor that filters nulls out of the nearest list.
11. query on cloud9 ide: js to coffee
    
    > Convert the highlighted text to coffeescript.
##

**Comment by orchid-hybrid** [comment]
Hello! I've tried context script for the first time and I thought it was great! Here is my full writeup:

---

signing in with persona/gmail was easy!

I tried out the tables example and saved them as csv, worked fine.

try the hello world example, couldn't find a new script button so I typed "new script" and it has 2 results! chose create script

when I pressed save I got a a json error:
{"readyState":4,"responseText":... is not of a type(s) object, "status":400,"statusText":"Bad Request"}

tried again and it worked, figured out the error came from deleting the "q: " in the trigger. [maybe the JSON error could be turned into a human readable error message explaining that?]

tried out the word count script and checked out its source code. it was a bit complex so I checked out the 'get page text' source code script next.

I saw a lot of pages that extract information from a page but none that edit the page itself, so I looked through the source for what features cxsAPI has.

I didn't find a reference for what cxsAPI can do. but I did notice this dead link: https://github.com/contextscript/contextscript/blob/master/jspm.io when reading https://github.com/contextscript/contextscript/blob/master/publishing.md

Decided to make a script to hilight all occurences of a word in article by basing it on getText and using the nodeMappings. When I tried this: It displayed "undefined to undefined" so I wonder if there is a bug in that!

I wrote a script that hilights in yellow every occurence of the word quantum, and tells you how many it finds. You are welcome to include this as an example script if you like! Currently the word it  finds is hard coded: It would be nice to take the word to find as a parameter but I didn't see any examples of that.

It was very useful to be able to edit my script on the context script webpage itself then switch back to test it on the wikipedia article.

Here is the script itself:
- https://contextscript.com/contextscripts/oZJlxxhgT_ixJM5NsrfzOA-1435419324138 mirrored here https://gist.github.com/orchid-hybrid/3edf0f16748a7c17a306

<img src="http://i.imgur.com/oj9254t.png"></img>

**Comment by nathanathan** [comment]
@orchid-hybrid Thanks a ton for the feedback. It has been enlightening. I'll work on the issues you mentioned. Documentation for cxsAPI is my next priority.

To take the word as a parameter, put the part of the trigger phrase you want to be a parameter in brackets like this: `q: "find word {{word}}"` Then you can access the parameter in the cxsAPI args property: `cxsAPI.args.word` Here's an example: https://contextscript.com/contextscripts/1kKhoUfQS0yJ9vn-xJZvKQ-1422683873975

I can't find a way to reproduce the "undefined to undefined" bug  you reported in the getText nodeMappings. It would help a lot if you could provide instructions on how to make it happen. I noticed a bug in your script that causes dom nodes to be removed which might be the root of the problem. On [this line](https://gist.github.com/orchid-hybrid/3edf0f16748a7c17a306#file-gistfile1-txt-L16) if the node has any sibling elements, setting the innerHTML of its parent will cause them to be deleted. The "plot location" script [here](https://github.com/contextscript/contextscript/blob/master/contextScripts/plotLocations.md) contains some code for doing highlighting based on character offsets which you might find useful.

Before publishing your word search script, I would like to see it do something a "ctrl+f" search can't do. What you've created so far would be an excellent basis for making a "highlight quantum mechanics keywords" script that highlights a variety of keywords related to the subject. Another possibility would be to make it into a "find regular expression {{regex}}" script.

When the script is ready, create a pull request adding it to [this directory](https://github.com/contextscript/contextscript/tree/master/contextScripts) and I will award the bounty to you.

**Comment by orchid-hybrid** [comment]
Thank you for the feedback!

I've used that trick to have the script accept a regex parameter - and looked into how plot location avoids deleting child nodes, this improved the script a lot! Now it searches for all instances of a user supplied regex and highlights them.

regarding "undefined to undefined", you were right: It was my mistake in forgetting .node so there is no issue there.

Here is the PR itself: https://github.com/contextscript/contextscript/pull/2

**Comment by nathanathan** [comment]
Nice work! I'll take a closer look at your PR on Friday before merging it. I'll award the bounty now though. (I think you need to click a button to claim it first).
